spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wydemo
#    password: root
    #url: jdbc:mysql://cdb-4cc35yyq.cd.tencentcdb.com:10031/WYDemo?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/wydemo?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true
    hibernate:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
#  jackson:
#    default-property-inclusion: non_null
server:
  port: 8886
  context-path: /wy

uploadPath:
  /usr/java/wyxyScript/image/
